// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: message_query.proto

package im

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRecordRequest) Reset() {
	*x = MessageRecordRequest{}
	mi := &file_message_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecordRequest) ProtoMessage() {}

func (x *MessageRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecordRequest.ProtoReflect.Descriptor instead.
func (*MessageRecordRequest) Descriptor() ([]byte, []int) {
	return file_message_query_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRecordRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type MessageRecordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 查询成功但不存在为 false；查询失败必须返回 gRPC error。
	Found          bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	MessageId      string `protobuf:"bytes,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
	ConversationId string `protobuf:"bytes,3,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	SenderId       string `protobuf:"bytes,4,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ReceiverId     string `protobuf:"bytes,5,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	CreatedAt      int64  `protobuf:"varint,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"` // UnixNano
	ChatType       int32  `protobuf:"varint,7,opt,name=chatType,proto3" json:"chatType,omitempty"`
	MsgType        int32  `protobuf:"varint,8,opt,name=msgType,proto3" json:"msgType,omitempty"`
	ReadState      string `protobuf:"bytes,9,opt,name=readState,proto3" json:"readState,omitempty"` // known | unknown | approximate
	ReadStateNote  string `protobuf:"bytes,10,opt,name=readStateNote,proto3" json:"readStateNote,omitempty"`
	ObservedAt     int64  `protobuf:"varint,11,opt,name=observedAt,proto3" json:"observedAt,omitempty"` // UnixNano
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageRecordResponse) Reset() {
	*x = MessageRecordResponse{}
	mi := &file_message_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecordResponse) ProtoMessage() {}

func (x *MessageRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecordResponse.ProtoReflect.Descriptor instead.
func (*MessageRecordResponse) Descriptor() ([]byte, []int) {
	return file_message_query_proto_rawDescGZIP(), []int{1}
}

func (x *MessageRecordResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *MessageRecordResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageRecordResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageRecordResponse) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageRecordResponse) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *MessageRecordResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MessageRecordResponse) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *MessageRecordResponse) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MessageRecordResponse) GetReadState() string {
	if x != nil {
		return x.ReadState
	}
	return ""
}

func (x *MessageRecordResponse) GetReadStateNote() string {
	if x != nil {
		return x.ReadStateNote
	}
	return ""
}

func (x *MessageRecordResponse) GetObservedAt() int64 {
	if x != nil {
		return x.ObservedAt
	}
	return 0
}

type MessageSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,2,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"` // 必填 UnixNano，最长 7 天
	EndTime       int64                  `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"` // 默认 10，最多 20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSearchRequest) Reset() {
	*x = MessageSearchRequest{}
	mi := &file_message_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSearchRequest) ProtoMessage() {}

func (x *MessageSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSearchRequest.ProtoReflect.Descriptor instead.
func (*MessageSearchRequest) Descriptor() ([]byte, []int) {
	return file_message_query_proto_rawDescGZIP(), []int{2}
}

func (x *MessageSearchRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageSearchRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *MessageSearchRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MessageSearchRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *MessageSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MessageQueryReference struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ReceiverId     string                 `protobuf:"bytes,4,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageQueryReference) Reset() {
	*x = MessageQueryReference{}
	mi := &file_message_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageQueryReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageQueryReference) ProtoMessage() {}

func (x *MessageQueryReference) ProtoReflect() protoreflect.Message {
	mi := &file_message_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageQueryReference.ProtoReflect.Descriptor instead.
func (*MessageQueryReference) Descriptor() ([]byte, []int) {
	return file_message_query_proto_rawDescGZIP(), []int{3}
}

func (x *MessageQueryReference) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageQueryReference) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageQueryReference) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageQueryReference) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *MessageQueryReference) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type MessageSearchResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Messages      []*MessageQueryReference `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Truncated     bool                     `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	ObservedAt    int64                    `protobuf:"varint,3,opt,name=observedAt,proto3" json:"observedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSearchResponse) Reset() {
	*x = MessageSearchResponse{}
	mi := &file_message_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSearchResponse) ProtoMessage() {}

func (x *MessageSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSearchResponse.ProtoReflect.Descriptor instead.
func (*MessageSearchResponse) Descriptor() ([]byte, []int) {
	return file_message_query_proto_rawDescGZIP(), []int{4}
}

func (x *MessageSearchResponse) GetMessages() []*MessageQueryReference {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *MessageSearchResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *MessageSearchResponse) GetObservedAt() int64 {
	if x != nil {
		return x.ObservedAt
	}
	return 0
}

var File_message_query_proto protoreflect.FileDescriptor

const file_message_query_proto_rawDesc = "" +
	"\n" +
	"\x13message_query.proto\x12\x02im\"4\n" +
	"\x14MessageRecordRequest\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\tR\tmessageId\"\xe7\x02\n" +
	"\x15MessageRecordResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1c\n" +
	"\tmessageId\x18\x02 \x01(\tR\tmessageId\x12&\n" +
	"\x0econversationId\x18\x03 \x01(\tR\x0econversationId\x12\x1a\n" +
	"\bsenderId\x18\x04 \x01(\tR\bsenderId\x12\x1e\n" +
	"\n" +
	"receiverId\x18\x05 \x01(\tR\n" +
	"receiverId\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\bchatType\x18\a \x01(\x05R\bchatType\x12\x18\n" +
	"\amsgType\x18\b \x01(\x05R\amsgType\x12\x1c\n" +
	"\treadState\x18\t \x01(\tR\treadState\x12$\n" +
	"\rreadStateNote\x18\n" +
	" \x01(\tR\rreadStateNote\x12\x1e\n" +
	"\n" +
	"observedAt\x18\v \x01(\x03R\n" +
	"observedAt\"\xa0\x01\n" +
	"\x14MessageSearchRequest\x12\x1a\n" +
	"\bsenderId\x18\x01 \x01(\tR\bsenderId\x12\x1e\n" +
	"\n" +
	"receiverId\x18\x02 \x01(\tR\n" +
	"receiverId\x12\x1c\n" +
	"\tstartTime\x18\x03 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x04 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\xb7\x01\n" +
	"\x15MessageQueryReference\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\tR\tmessageId\x12&\n" +
	"\x0econversationId\x18\x02 \x01(\tR\x0econversationId\x12\x1a\n" +
	"\bsenderId\x18\x03 \x01(\tR\bsenderId\x12\x1e\n" +
	"\n" +
	"receiverId\x18\x04 \x01(\tR\n" +
	"receiverId\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x03R\tcreatedAt\"\x8c\x01\n" +
	"\x15MessageSearchResponse\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.im.MessageQueryReferenceR\bmessages\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\x12\x1e\n" +
	"\n" +
	"observedAt\x18\x03 \x01(\x03R\n" +
	"observedAt2\x9e\x01\n" +
	"\fMessageQuery\x12G\n" +
	"\x10GetMessageRecord\x12\x18.im.MessageRecordRequest\x1a\x19.im.MessageRecordResponse\x12E\n" +
	"\x0eSearchMessages\x12\x18.im.MessageSearchRequest\x1a\x19.im.MessageSearchResponseB%Z#github.com/IM_System/apps/im/rpc/imb\x06proto3"

var (
	file_message_query_proto_rawDescOnce sync.Once
	file_message_query_proto_rawDescData []byte
)

func file_message_query_proto_rawDescGZIP() []byte {
	file_message_query_proto_rawDescOnce.Do(func() {
		file_message_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_query_proto_rawDesc), len(file_message_query_proto_rawDesc)))
	})
	return file_message_query_proto_rawDescData
}

var file_message_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_message_query_proto_goTypes = []any{
	(*MessageRecordRequest)(nil),  // 0: im.MessageRecordRequest
	(*MessageRecordResponse)(nil), // 1: im.MessageRecordResponse
	(*MessageSearchRequest)(nil),  // 2: im.MessageSearchRequest
	(*MessageQueryReference)(nil), // 3: im.MessageQueryReference
	(*MessageSearchResponse)(nil), // 4: im.MessageSearchResponse
}
var file_message_query_proto_depIdxs = []int32{
	3, // 0: im.MessageSearchResponse.messages:type_name -> im.MessageQueryReference
	0, // 1: im.MessageQuery.GetMessageRecord:input_type -> im.MessageRecordRequest
	2, // 2: im.MessageQuery.SearchMessages:input_type -> im.MessageSearchRequest
	1, // 3: im.MessageQuery.GetMessageRecord:output_type -> im.MessageRecordResponse
	4, // 4: im.MessageQuery.SearchMessages:output_type -> im.MessageSearchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_query_proto_init() }
func file_message_query_proto_init() {
	if File_message_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_query_proto_rawDesc), len(file_message_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_query_proto_goTypes,
		DependencyIndexes: file_message_query_proto_depIdxs,
		MessageInfos:      file_message_query_proto_msgTypes,
	}.Build()
	File_message_query_proto = out.File
	file_message_query_proto_goTypes = nil
	file_message_query_proto_depIdxs = nil
}
