// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: message_query.proto

package im

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageQuery_GetMessageRecord_FullMethodName = "/im.MessageQuery/GetMessageRecord"
	MessageQuery_SearchMessages_FullMethodName   = "/im.MessageQuery/SearchMessages"
)

// MessageQueryClient is the client API for MessageQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 消息领域只读查询。与 Im 的聊天业务契约分离，复用同一 RPC 进程。
// 当前仅供受信任内部服务使用，不是普通用户或公开 SDK 接口。
type MessageQueryClient interface {
	GetMessageRecord(ctx context.Context, in *MessageRecordRequest, opts ...grpc.CallOption) (*MessageRecordResponse, error)
	SearchMessages(ctx context.Context, in *MessageSearchRequest, opts ...grpc.CallOption) (*MessageSearchResponse, error)
}

type messageQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageQueryClient(cc grpc.ClientConnInterface) MessageQueryClient {
	return &messageQueryClient{cc}
}

func (c *messageQueryClient) GetMessageRecord(ctx context.Context, in *MessageRecordRequest, opts ...grpc.CallOption) (*MessageRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageRecordResponse)
	err := c.cc.Invoke(ctx, MessageQuery_GetMessageRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageQueryClient) SearchMessages(ctx context.Context, in *MessageSearchRequest, opts ...grpc.CallOption) (*MessageSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageSearchResponse)
	err := c.cc.Invoke(ctx, MessageQuery_SearchMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageQueryServer is the server API for MessageQuery service.
// All implementations must embed UnimplementedMessageQueryServer
// for forward compatibility.
//
// 消息领域只读查询。与 Im 的聊天业务契约分离，复用同一 RPC 进程。
// 当前仅供受信任内部服务使用，不是普通用户或公开 SDK 接口。
type MessageQueryServer interface {
	GetMessageRecord(context.Context, *MessageRecordRequest) (*MessageRecordResponse, error)
	SearchMessages(context.Context, *MessageSearchRequest) (*MessageSearchResponse, error)
	mustEmbedUnimplementedMessageQueryServer()
}

// UnimplementedMessageQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageQueryServer struct{}

func (UnimplementedMessageQueryServer) GetMessageRecord(context.Context, *MessageRecordRequest) (*MessageRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageRecord not implemented")
}
func (UnimplementedMessageQueryServer) SearchMessages(context.Context, *MessageSearchRequest) (*MessageSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchMessages not implemented")
}
func (UnimplementedMessageQueryServer) mustEmbedUnimplementedMessageQueryServer() {}
func (UnimplementedMessageQueryServer) testEmbeddedByValue()                      {}

// UnsafeMessageQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageQueryServer will
// result in compilation errors.
type UnsafeMessageQueryServer interface {
	mustEmbedUnimplementedMessageQueryServer()
}

func RegisterMessageQueryServer(s grpc.ServiceRegistrar, srv MessageQueryServer) {
	// If the following call panics, it indicates UnimplementedMessageQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageQuery_ServiceDesc, srv)
}

func _MessageQuery_GetMessageRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueryServer).GetMessageRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQuery_GetMessageRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueryServer).GetMessageRecord(ctx, req.(*MessageRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageQuery_SearchMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueryServer).SearchMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQuery_SearchMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueryServer).SearchMessages(ctx, req.(*MessageSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageQuery_ServiceDesc is the grpc.ServiceDesc for MessageQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "im.MessageQuery",
	HandlerType: (*MessageQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessageRecord",
			Handler:    _MessageQuery_GetMessageRecord_Handler,
		},
		{
			MethodName: "SearchMessages",
			Handler:    _MessageQuery_SearchMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message_query.proto",
}
