// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package socialmodels

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendsFieldNames          = builder.RawFieldNames(&Friends{})
	friendsRows                = strings.Join(friendsFieldNames, ",")
	friendsRowsExpectAutoSet   = strings.Join(stringx.Remove(friendsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendsRowsWithPlaceHolder = strings.Join(stringx.Remove(friendsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendsIdPrefix              = "cache:friends:id:"
	cacheFriendsUserIdFriendUidPrefix = "cache:friends:userId:friendUid:"
)

type (
	friendsModel interface {
		Insert(ctx context.Context, data *Friends) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Friends, error)
		FindOneByUserIdFriendUid(ctx context.Context, userId string, friendUid string) (*Friends, error)
		Update(ctx context.Context, data *Friends) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFriendsModel struct {
		sqlc.CachedConn
		table string
	}

	Friends struct {
		Id        uint64         `db:"id"`
		UserId    string         `db:"user_id"`    // 用户ID
		FriendUid string         `db:"friend_uid"` // 好友ID
		Remark    sql.NullString `db:"remark"`     // 好友备注
		AddSource sql.NullInt64  `db:"add_source"` // 添加来源(如1:搜索, 2:群聊等)
		CreatedAt time.Time      `db:"created_at"` // 添加时间
	}
)

func newFriendsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendsModel {
	return &defaultFriendsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friends`",
	}
}

func (m *defaultFriendsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	friendsIdKey := fmt.Sprintf("%s%v", cacheFriendsIdPrefix, id)
	friendsUserIdFriendUidKey := fmt.Sprintf("%s%v:%v", cacheFriendsUserIdFriendUidPrefix, data.UserId, data.FriendUid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendsIdKey, friendsUserIdFriendUidKey)
	return err
}

func (m *defaultFriendsModel) FindOne(ctx context.Context, id uint64) (*Friends, error) {
	friendsIdKey := fmt.Sprintf("%s%v", cacheFriendsIdPrefix, id)
	var resp Friends
	err := m.QueryRowCtx(ctx, &resp, friendsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendsModel) FindOneByUserIdFriendUid(ctx context.Context, userId string, friendUid string) (*Friends, error) {
	friendsUserIdFriendUidKey := fmt.Sprintf("%s%v:%v", cacheFriendsUserIdFriendUidPrefix, userId, friendUid)
	var resp Friends
	err := m.QueryRowIndexCtx(ctx, &resp, friendsUserIdFriendUidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `friend_uid` = ? limit 1", friendsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, friendUid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendsModel) Insert(ctx context.Context, data *Friends) (sql.Result, error) {
	friendsIdKey := fmt.Sprintf("%s%v", cacheFriendsIdPrefix, data.Id)
	friendsUserIdFriendUidKey := fmt.Sprintf("%s%v:%v", cacheFriendsUserIdFriendUidPrefix, data.UserId, data.FriendUid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, friendsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FriendUid, data.Remark, data.AddSource)
	}, friendsIdKey, friendsUserIdFriendUidKey)
	return ret, err
}

func (m *defaultFriendsModel) Update(ctx context.Context, newData *Friends) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	friendsIdKey := fmt.Sprintf("%s%v", cacheFriendsIdPrefix, data.Id)
	friendsUserIdFriendUidKey := fmt.Sprintf("%s%v:%v", cacheFriendsUserIdFriendUidPrefix, data.UserId, data.FriendUid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.FriendUid, newData.Remark, newData.AddSource, newData.Id)
	}, friendsIdKey, friendsUserIdFriendUidKey)
	return err
}

func (m *defaultFriendsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendsIdPrefix, primary)
}

func (m *defaultFriendsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendsModel) tableName() string {
	return m.table
}
