// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: operations.proto

package operations

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObservationQuery_GetMessageTimeline_FullMethodName        = "/operations.ObservationQuery/GetMessageTimeline"
	ObservationQuery_GetDeliveryTimeline_FullMethodName       = "/operations.ObservationQuery/GetDeliveryTimeline"
	ObservationQuery_GetConnectionObservations_FullMethodName = "/operations.ObservationQuery/GetConnectionObservations"
	ObservationQuery_GetCapabilities_FullMethodName           = "/operations.ObservationQuery/GetCapabilities"
)

// ObservationQueryClient is the client API for ObservationQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ObservationQuery：正式内部观测契约，不包含业务对象查询。
type ObservationQueryClient interface {
	GetMessageTimeline(ctx context.Context, in *GetMessageTimelineRequest, opts ...grpc.CallOption) (*GetMessageTimelineResponse, error)
	GetDeliveryTimeline(ctx context.Context, in *GetDeliveryTimelineRequest, opts ...grpc.CallOption) (*GetDeliveryTimelineResponse, error)
	GetConnectionObservations(ctx context.Context, in *GetConnectionObservationsRequest, opts ...grpc.CallOption) (*GetConnectionObservationsResponse, error)
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
}

type observationQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewObservationQueryClient(cc grpc.ClientConnInterface) ObservationQueryClient {
	return &observationQueryClient{cc}
}

func (c *observationQueryClient) GetMessageTimeline(ctx context.Context, in *GetMessageTimelineRequest, opts ...grpc.CallOption) (*GetMessageTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageTimelineResponse)
	err := c.cc.Invoke(ctx, ObservationQuery_GetMessageTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observationQueryClient) GetDeliveryTimeline(ctx context.Context, in *GetDeliveryTimelineRequest, opts ...grpc.CallOption) (*GetDeliveryTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeliveryTimelineResponse)
	err := c.cc.Invoke(ctx, ObservationQuery_GetDeliveryTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observationQueryClient) GetConnectionObservations(ctx context.Context, in *GetConnectionObservationsRequest, opts ...grpc.CallOption) (*GetConnectionObservationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionObservationsResponse)
	err := c.cc.Invoke(ctx, ObservationQuery_GetConnectionObservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observationQueryClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, ObservationQuery_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObservationQueryServer is the server API for ObservationQuery service.
// All implementations must embed UnimplementedObservationQueryServer
// for forward compatibility.
//
// ObservationQuery：正式内部观测契约，不包含业务对象查询。
type ObservationQueryServer interface {
	GetMessageTimeline(context.Context, *GetMessageTimelineRequest) (*GetMessageTimelineResponse, error)
	GetDeliveryTimeline(context.Context, *GetDeliveryTimelineRequest) (*GetDeliveryTimelineResponse, error)
	GetConnectionObservations(context.Context, *GetConnectionObservationsRequest) (*GetConnectionObservationsResponse, error)
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	mustEmbedUnimplementedObservationQueryServer()
}

// UnimplementedObservationQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObservationQueryServer struct{}

func (UnimplementedObservationQueryServer) GetMessageTimeline(context.Context, *GetMessageTimelineRequest) (*GetMessageTimelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageTimeline not implemented")
}
func (UnimplementedObservationQueryServer) GetDeliveryTimeline(context.Context, *GetDeliveryTimelineRequest) (*GetDeliveryTimelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryTimeline not implemented")
}
func (UnimplementedObservationQueryServer) GetConnectionObservations(context.Context, *GetConnectionObservationsRequest) (*GetConnectionObservationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectionObservations not implemented")
}
func (UnimplementedObservationQueryServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedObservationQueryServer) mustEmbedUnimplementedObservationQueryServer() {}
func (UnimplementedObservationQueryServer) testEmbeddedByValue()                          {}

// UnsafeObservationQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObservationQueryServer will
// result in compilation errors.
type UnsafeObservationQueryServer interface {
	mustEmbedUnimplementedObservationQueryServer()
}

func RegisterObservationQueryServer(s grpc.ServiceRegistrar, srv ObservationQueryServer) {
	// If the following call panics, it indicates UnimplementedObservationQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObservationQuery_ServiceDesc, srv)
}

func _ObservationQuery_GetMessageTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationQueryServer).GetMessageTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationQuery_GetMessageTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationQueryServer).GetMessageTimeline(ctx, req.(*GetMessageTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservationQuery_GetDeliveryTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationQueryServer).GetDeliveryTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationQuery_GetDeliveryTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationQueryServer).GetDeliveryTimeline(ctx, req.(*GetDeliveryTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservationQuery_GetConnectionObservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionObservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationQueryServer).GetConnectionObservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationQuery_GetConnectionObservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationQueryServer).GetConnectionObservations(ctx, req.(*GetConnectionObservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservationQuery_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationQueryServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationQuery_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationQueryServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObservationQuery_ServiceDesc is the grpc.ServiceDesc for ObservationQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObservationQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operations.ObservationQuery",
	HandlerType: (*ObservationQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessageTimeline",
			Handler:    _ObservationQuery_GetMessageTimeline_Handler,
		},
		{
			MethodName: "GetDeliveryTimeline",
			Handler:    _ObservationQuery_GetDeliveryTimeline_Handler,
		},
		{
			MethodName: "GetConnectionObservations",
			Handler:    _ObservationQuery_GetConnectionObservations_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _ObservationQuery_GetCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operations.proto",
}

const (
	OperationsQuery_SearchMessages_FullMethodName            = "/operations.OperationsQuery/SearchMessages"
	OperationsQuery_FindUserReference_FullMethodName         = "/operations.OperationsQuery/FindUserReference"
	OperationsQuery_GetMessageRecord_FullMethodName          = "/operations.OperationsQuery/GetMessageRecord"
	OperationsQuery_GetMessageTimeline_FullMethodName        = "/operations.OperationsQuery/GetMessageTimeline"
	OperationsQuery_GetDeliveryTimeline_FullMethodName       = "/operations.OperationsQuery/GetDeliveryTimeline"
	OperationsQuery_GetConnectionObservations_FullMethodName = "/operations.OperationsQuery/GetConnectionObservations"
	OperationsQuery_GetCapabilities_FullMethodName           = "/operations.OperationsQuery/GetCapabilities"
)

// OperationsQueryClient is the client API for OperationsQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OperationsQuery：迁移期兼容契约，供尚未切换的客户端使用。
// 时间字段一律 int64 UnixNano（纳秒），禁止与毫秒/秒混用。
// 只读红线：永久禁止 ExecuteSQL / ExecuteShell / Resend / Modify / Delete / KickUser 等写能力。
type OperationsQueryClient interface {
	// 迁移兼容入口：转调 im.MessageQuery，后续停用，不再拥有业务查询实现。
	SearchMessages(ctx context.Context, in *SearchMessagesRequest, opts ...grpc.CallOption) (*SearchMessagesResponse, error)
	// 迁移兼容入口：转调 user.UserQuery；响应仍为最小脱敏投影。
	FindUserReference(ctx context.Context, in *FindUserReferenceRequest, opts ...grpc.CallOption) (*FindUserReferenceResponse, error)
	// 迁移兼容入口：转调 im.MessageQuery，再可选补充观测可用性。
	GetMessageRecord(ctx context.Context, in *GetMessageRecordRequest, opts ...grpc.CallOption) (*GetMessageRecordResponse, error)
	// 消息生命周期事件流
	GetMessageTimeline(ctx context.Context, in *GetMessageTimelineRequest, opts ...grpc.CallOption) (*GetMessageTimelineResponse, error)
	// 投递侧事件流（群聊按接收方拆分）
	GetDeliveryTimeline(ctx context.Context, in *GetDeliveryTimelineRequest, opts ...grpc.CallOption) (*GetDeliveryTimelineResponse, error)
	// 连接状态历史观察（区分当前在线与历史在线）
	GetConnectionObservations(ctx context.Context, in *GetConnectionObservationsRequest, opts ...grpc.CallOption) (*GetConnectionObservationsResponse, error)
	// 诚实的能力声明，取值仅 supported|partial|unsupported
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
}

type operationsQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationsQueryClient(cc grpc.ClientConnInterface) OperationsQueryClient {
	return &operationsQueryClient{cc}
}

func (c *operationsQueryClient) SearchMessages(ctx context.Context, in *SearchMessagesRequest, opts ...grpc.CallOption) (*SearchMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchMessagesResponse)
	err := c.cc.Invoke(ctx, OperationsQuery_SearchMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsQueryClient) FindUserReference(ctx context.Context, in *FindUserReferenceRequest, opts ...grpc.CallOption) (*FindUserReferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindUserReferenceResponse)
	err := c.cc.Invoke(ctx, OperationsQuery_FindUserReference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsQueryClient) GetMessageRecord(ctx context.Context, in *GetMessageRecordRequest, opts ...grpc.CallOption) (*GetMessageRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageRecordResponse)
	err := c.cc.Invoke(ctx, OperationsQuery_GetMessageRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsQueryClient) GetMessageTimeline(ctx context.Context, in *GetMessageTimelineRequest, opts ...grpc.CallOption) (*GetMessageTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageTimelineResponse)
	err := c.cc.Invoke(ctx, OperationsQuery_GetMessageTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsQueryClient) GetDeliveryTimeline(ctx context.Context, in *GetDeliveryTimelineRequest, opts ...grpc.CallOption) (*GetDeliveryTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeliveryTimelineResponse)
	err := c.cc.Invoke(ctx, OperationsQuery_GetDeliveryTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsQueryClient) GetConnectionObservations(ctx context.Context, in *GetConnectionObservationsRequest, opts ...grpc.CallOption) (*GetConnectionObservationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionObservationsResponse)
	err := c.cc.Invoke(ctx, OperationsQuery_GetConnectionObservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsQueryClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, OperationsQuery_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationsQueryServer is the server API for OperationsQuery service.
// All implementations must embed UnimplementedOperationsQueryServer
// for forward compatibility.
//
// OperationsQuery：迁移期兼容契约，供尚未切换的客户端使用。
// 时间字段一律 int64 UnixNano（纳秒），禁止与毫秒/秒混用。
// 只读红线：永久禁止 ExecuteSQL / ExecuteShell / Resend / Modify / Delete / KickUser 等写能力。
type OperationsQueryServer interface {
	// 迁移兼容入口：转调 im.MessageQuery，后续停用，不再拥有业务查询实现。
	SearchMessages(context.Context, *SearchMessagesRequest) (*SearchMessagesResponse, error)
	// 迁移兼容入口：转调 user.UserQuery；响应仍为最小脱敏投影。
	FindUserReference(context.Context, *FindUserReferenceRequest) (*FindUserReferenceResponse, error)
	// 迁移兼容入口：转调 im.MessageQuery，再可选补充观测可用性。
	GetMessageRecord(context.Context, *GetMessageRecordRequest) (*GetMessageRecordResponse, error)
	// 消息生命周期事件流
	GetMessageTimeline(context.Context, *GetMessageTimelineRequest) (*GetMessageTimelineResponse, error)
	// 投递侧事件流（群聊按接收方拆分）
	GetDeliveryTimeline(context.Context, *GetDeliveryTimelineRequest) (*GetDeliveryTimelineResponse, error)
	// 连接状态历史观察（区分当前在线与历史在线）
	GetConnectionObservations(context.Context, *GetConnectionObservationsRequest) (*GetConnectionObservationsResponse, error)
	// 诚实的能力声明，取值仅 supported|partial|unsupported
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	mustEmbedUnimplementedOperationsQueryServer()
}

// UnimplementedOperationsQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationsQueryServer struct{}

func (UnimplementedOperationsQueryServer) SearchMessages(context.Context, *SearchMessagesRequest) (*SearchMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchMessages not implemented")
}
func (UnimplementedOperationsQueryServer) FindUserReference(context.Context, *FindUserReferenceRequest) (*FindUserReferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindUserReference not implemented")
}
func (UnimplementedOperationsQueryServer) GetMessageRecord(context.Context, *GetMessageRecordRequest) (*GetMessageRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageRecord not implemented")
}
func (UnimplementedOperationsQueryServer) GetMessageTimeline(context.Context, *GetMessageTimelineRequest) (*GetMessageTimelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageTimeline not implemented")
}
func (UnimplementedOperationsQueryServer) GetDeliveryTimeline(context.Context, *GetDeliveryTimelineRequest) (*GetDeliveryTimelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryTimeline not implemented")
}
func (UnimplementedOperationsQueryServer) GetConnectionObservations(context.Context, *GetConnectionObservationsRequest) (*GetConnectionObservationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectionObservations not implemented")
}
func (UnimplementedOperationsQueryServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedOperationsQueryServer) mustEmbedUnimplementedOperationsQueryServer() {}
func (UnimplementedOperationsQueryServer) testEmbeddedByValue()                         {}

// UnsafeOperationsQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationsQueryServer will
// result in compilation errors.
type UnsafeOperationsQueryServer interface {
	mustEmbedUnimplementedOperationsQueryServer()
}

func RegisterOperationsQueryServer(s grpc.ServiceRegistrar, srv OperationsQueryServer) {
	// If the following call panics, it indicates UnimplementedOperationsQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperationsQuery_ServiceDesc, srv)
}

func _OperationsQuery_SearchMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsQueryServer).SearchMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsQuery_SearchMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsQueryServer).SearchMessages(ctx, req.(*SearchMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsQuery_FindUserReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsQueryServer).FindUserReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsQuery_FindUserReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsQueryServer).FindUserReference(ctx, req.(*FindUserReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsQuery_GetMessageRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsQueryServer).GetMessageRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsQuery_GetMessageRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsQueryServer).GetMessageRecord(ctx, req.(*GetMessageRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsQuery_GetMessageTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsQueryServer).GetMessageTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsQuery_GetMessageTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsQueryServer).GetMessageTimeline(ctx, req.(*GetMessageTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsQuery_GetDeliveryTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsQueryServer).GetDeliveryTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsQuery_GetDeliveryTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsQueryServer).GetDeliveryTimeline(ctx, req.(*GetDeliveryTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsQuery_GetConnectionObservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionObservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsQueryServer).GetConnectionObservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsQuery_GetConnectionObservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsQueryServer).GetConnectionObservations(ctx, req.(*GetConnectionObservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsQuery_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsQueryServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsQuery_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsQueryServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperationsQuery_ServiceDesc is the grpc.ServiceDesc for OperationsQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperationsQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operations.OperationsQuery",
	HandlerType: (*OperationsQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchMessages",
			Handler:    _OperationsQuery_SearchMessages_Handler,
		},
		{
			MethodName: "FindUserReference",
			Handler:    _OperationsQuery_FindUserReference_Handler,
		},
		{
			MethodName: "GetMessageRecord",
			Handler:    _OperationsQuery_GetMessageRecord_Handler,
		},
		{
			MethodName: "GetMessageTimeline",
			Handler:    _OperationsQuery_GetMessageTimeline_Handler,
		},
		{
			MethodName: "GetDeliveryTimeline",
			Handler:    _OperationsQuery_GetDeliveryTimeline_Handler,
		},
		{
			MethodName: "GetConnectionObservations",
			Handler:    _OperationsQuery_GetConnectionObservations_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _OperationsQuery_GetCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operations.proto",
}
