// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: operations.proto

package operations

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObservationQuery_GetMessageTimeline_FullMethodName        = "/operations.ObservationQuery/GetMessageTimeline"
	ObservationQuery_GetDeliveryTimeline_FullMethodName       = "/operations.ObservationQuery/GetDeliveryTimeline"
	ObservationQuery_GetConnectionObservations_FullMethodName = "/operations.ObservationQuery/GetConnectionObservations"
	ObservationQuery_GetCapabilities_FullMethodName           = "/operations.ObservationQuery/GetCapabilities"
)

// ObservationQueryClient is the client API for ObservationQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ObservationQuery：正式内部观测契约，不包含业务对象查询。
// 只读边界：禁止 ExecuteSQL / ExecuteShell / Resend / Modify / Delete / KickUser。
type ObservationQueryClient interface {
	GetMessageTimeline(ctx context.Context, in *GetMessageTimelineRequest, opts ...grpc.CallOption) (*GetMessageTimelineResponse, error)
	GetDeliveryTimeline(ctx context.Context, in *GetDeliveryTimelineRequest, opts ...grpc.CallOption) (*GetDeliveryTimelineResponse, error)
	GetConnectionObservations(ctx context.Context, in *GetConnectionObservationsRequest, opts ...grpc.CallOption) (*GetConnectionObservationsResponse, error)
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
}

type observationQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewObservationQueryClient(cc grpc.ClientConnInterface) ObservationQueryClient {
	return &observationQueryClient{cc}
}

func (c *observationQueryClient) GetMessageTimeline(ctx context.Context, in *GetMessageTimelineRequest, opts ...grpc.CallOption) (*GetMessageTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageTimelineResponse)
	err := c.cc.Invoke(ctx, ObservationQuery_GetMessageTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observationQueryClient) GetDeliveryTimeline(ctx context.Context, in *GetDeliveryTimelineRequest, opts ...grpc.CallOption) (*GetDeliveryTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeliveryTimelineResponse)
	err := c.cc.Invoke(ctx, ObservationQuery_GetDeliveryTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observationQueryClient) GetConnectionObservations(ctx context.Context, in *GetConnectionObservationsRequest, opts ...grpc.CallOption) (*GetConnectionObservationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionObservationsResponse)
	err := c.cc.Invoke(ctx, ObservationQuery_GetConnectionObservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observationQueryClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, ObservationQuery_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObservationQueryServer is the server API for ObservationQuery service.
// All implementations must embed UnimplementedObservationQueryServer
// for forward compatibility.
//
// ObservationQuery：正式内部观测契约，不包含业务对象查询。
// 只读边界：禁止 ExecuteSQL / ExecuteShell / Resend / Modify / Delete / KickUser。
type ObservationQueryServer interface {
	GetMessageTimeline(context.Context, *GetMessageTimelineRequest) (*GetMessageTimelineResponse, error)
	GetDeliveryTimeline(context.Context, *GetDeliveryTimelineRequest) (*GetDeliveryTimelineResponse, error)
	GetConnectionObservations(context.Context, *GetConnectionObservationsRequest) (*GetConnectionObservationsResponse, error)
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	mustEmbedUnimplementedObservationQueryServer()
}

// UnimplementedObservationQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObservationQueryServer struct{}

func (UnimplementedObservationQueryServer) GetMessageTimeline(context.Context, *GetMessageTimelineRequest) (*GetMessageTimelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageTimeline not implemented")
}
func (UnimplementedObservationQueryServer) GetDeliveryTimeline(context.Context, *GetDeliveryTimelineRequest) (*GetDeliveryTimelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryTimeline not implemented")
}
func (UnimplementedObservationQueryServer) GetConnectionObservations(context.Context, *GetConnectionObservationsRequest) (*GetConnectionObservationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectionObservations not implemented")
}
func (UnimplementedObservationQueryServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedObservationQueryServer) mustEmbedUnimplementedObservationQueryServer() {}
func (UnimplementedObservationQueryServer) testEmbeddedByValue()                          {}

// UnsafeObservationQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObservationQueryServer will
// result in compilation errors.
type UnsafeObservationQueryServer interface {
	mustEmbedUnimplementedObservationQueryServer()
}

func RegisterObservationQueryServer(s grpc.ServiceRegistrar, srv ObservationQueryServer) {
	// If the following call panics, it indicates UnimplementedObservationQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObservationQuery_ServiceDesc, srv)
}

func _ObservationQuery_GetMessageTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationQueryServer).GetMessageTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationQuery_GetMessageTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationQueryServer).GetMessageTimeline(ctx, req.(*GetMessageTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservationQuery_GetDeliveryTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationQueryServer).GetDeliveryTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationQuery_GetDeliveryTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationQueryServer).GetDeliveryTimeline(ctx, req.(*GetDeliveryTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservationQuery_GetConnectionObservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionObservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationQueryServer).GetConnectionObservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationQuery_GetConnectionObservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationQueryServer).GetConnectionObservations(ctx, req.(*GetConnectionObservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObservationQuery_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObservationQueryServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObservationQuery_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObservationQueryServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObservationQuery_ServiceDesc is the grpc.ServiceDesc for ObservationQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObservationQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operations.ObservationQuery",
	HandlerType: (*ObservationQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessageTimeline",
			Handler:    _ObservationQuery_GetMessageTimeline_Handler,
		},
		{
			MethodName: "GetDeliveryTimeline",
			Handler:    _ObservationQuery_GetDeliveryTimeline_Handler,
		},
		{
			MethodName: "GetConnectionObservations",
			Handler:    _ObservationQuery_GetConnectionObservations_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _ObservationQuery_GetCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operations.proto",
}
