// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: operations.proto

package operations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventVersion    int32                  `protobuf:"varint,2,opt,name=eventVersion,proto3" json:"eventVersion,omitempty"`
	EventType       string                 `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType,omitempty"`
	MessageId       string                 `protobuf:"bytes,4,opt,name=messageId,proto3" json:"messageId,omitempty"`
	ClientMessageId string                 `protobuf:"bytes,5,opt,name=clientMessageId,proto3" json:"clientMessageId,omitempty"`
	CorrelationId   string                 `protobuf:"bytes,6,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	ConversationId  string                 `protobuf:"bytes,7,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	SenderId        string                 `protobuf:"bytes,8,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ReceiverId      string                 `protobuf:"bytes,9,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	AttemptId       string                 `protobuf:"bytes,10,opt,name=attemptId,proto3" json:"attemptId,omitempty"`
	OccurredAt      int64                  `protobuf:"varint,11,opt,name=occurredAt,proto3" json:"occurredAt,omitempty"` // UnixNano
	Source          string                 `protobuf:"bytes,12,opt,name=source,proto3" json:"source,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,13,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Sequence        int64                  `protobuf:"varint,14,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,15,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{0}
}

func (x *MessageEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MessageEvent) GetEventVersion() int32 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *MessageEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MessageEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageEvent) GetClientMessageId() string {
	if x != nil {
		return x.ClientMessageId
	}
	return ""
}

func (x *MessageEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *MessageEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageEvent) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *MessageEvent) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *MessageEvent) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *MessageEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MessageEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *MessageEvent) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MessageEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetMessageTimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"` // UnixNano，0=不限
	EndTime       int64                  `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`     // UnixNano，0=不限
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageTimelineRequest) Reset() {
	*x = GetMessageTimelineRequest{}
	mi := &file_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageTimelineRequest) ProtoMessage() {}

func (x *GetMessageTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageTimelineRequest.ProtoReflect.Descriptor instead.
func (*GetMessageTimelineRequest) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessageTimelineRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetMessageTimelineRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetMessageTimelineRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetMessageTimelineRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessageTimelineRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetMessageTimelineResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Events         []*MessageEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Complete       bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	Truncated      bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	NextCursor     string                 `protobuf:"bytes,4,opt,name=nextCursor,proto3" json:"nextCursor,omitempty"`
	MessageId      string                 `protobuf:"bytes,5,opt,name=messageId,proto3" json:"messageId,omitempty"`
	CoverageStatus string                 `protobuf:"bytes,6,opt,name=coverageStatus,proto3" json:"coverageStatus,omitempty"` // complete | partial | unknown
	EventsDropped  uint64                 `protobuf:"varint,7,opt,name=eventsDropped,proto3" json:"eventsDropped,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMessageTimelineResponse) Reset() {
	*x = GetMessageTimelineResponse{}
	mi := &file_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageTimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageTimelineResponse) ProtoMessage() {}

func (x *GetMessageTimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageTimelineResponse.ProtoReflect.Descriptor instead.
func (*GetMessageTimelineResponse) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessageTimelineResponse) GetEvents() []*MessageEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetMessageTimelineResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *GetMessageTimelineResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *GetMessageTimelineResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetMessageTimelineResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetMessageTimelineResponse) GetCoverageStatus() string {
	if x != nil {
		return x.CoverageStatus
	}
	return ""
}

func (x *GetMessageTimelineResponse) GetEventsDropped() uint64 {
	if x != nil {
		return x.EventsDropped
	}
	return 0
}

type GetDeliveryTimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,2,opt,name=receiverId,proto3" json:"receiverId,omitempty"` // 可选
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryTimelineRequest) Reset() {
	*x = GetDeliveryTimelineRequest{}
	mi := &file_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryTimelineRequest) ProtoMessage() {}

func (x *GetDeliveryTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryTimelineRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryTimelineRequest) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeliveryTimelineRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetDeliveryTimelineRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *GetDeliveryTimelineRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetDeliveryTimelineRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type DeliveryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=eventType,proto3" json:"eventType,omitempty"` // delivery_* / receiver_offline / ack_*
	MessageId     string                 `protobuf:"bytes,3,opt,name=messageId,proto3" json:"messageId,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,4,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	AttemptId     string                 `protobuf:"bytes,5,opt,name=attemptId,proto3" json:"attemptId,omitempty"`
	OccurredAt    int64                  `protobuf:"varint,6,opt,name=occurredAt,proto3" json:"occurredAt,omitempty"` // UnixNano
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,8,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Evidence      string                 `protobuf:"bytes,10,opt,name=evidence,proto3" json:"evidence,omitempty"` // gateway-write | transport-ack | offline-marker | legacy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryEvent) Reset() {
	*x = DeliveryEvent{}
	mi := &file_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryEvent) ProtoMessage() {}

func (x *DeliveryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryEvent.ProtoReflect.Descriptor instead.
func (*DeliveryEvent) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveryEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeliveryEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *DeliveryEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeliveryEvent) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *DeliveryEvent) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *DeliveryEvent) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *DeliveryEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DeliveryEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DeliveryEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DeliveryEvent) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

type GetDeliveryTimelineResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Events         []*DeliveryEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Complete       bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	Truncated      bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	NextCursor     string                 `protobuf:"bytes,4,opt,name=nextCursor,proto3" json:"nextCursor,omitempty"`
	MessageId      string                 `protobuf:"bytes,5,opt,name=messageId,proto3" json:"messageId,omitempty"`
	CoverageStatus string                 `protobuf:"bytes,6,opt,name=coverageStatus,proto3" json:"coverageStatus,omitempty"`
	EventsDropped  uint64                 `protobuf:"varint,7,opt,name=eventsDropped,proto3" json:"eventsDropped,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDeliveryTimelineResponse) Reset() {
	*x = GetDeliveryTimelineResponse{}
	mi := &file_operations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryTimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryTimelineResponse) ProtoMessage() {}

func (x *GetDeliveryTimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryTimelineResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryTimelineResponse) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeliveryTimelineResponse) GetEvents() []*DeliveryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetDeliveryTimelineResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *GetDeliveryTimelineResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *GetDeliveryTimelineResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetDeliveryTimelineResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetDeliveryTimelineResponse) GetCoverageStatus() string {
	if x != nil {
		return x.CoverageStatus
	}
	return ""
}

func (x *GetDeliveryTimelineResponse) GetEventsDropped() uint64 {
	if x != nil {
		return x.EventsDropped
	}
	return 0
}

type GetConnectionObservationsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	At             int64                  `protobuf:"varint,2,opt,name=at,proto3" json:"at,omitempty"`               // UnixNano 时间点；与时间范围互斥
	StartTime      int64                  `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"` // UnixNano
	EndTime        int64                  `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`     // UnixNano
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor         string                 `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IncludeCurrent bool                   `protobuf:"varint,7,opt,name=includeCurrent,proto3" json:"includeCurrent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConnectionObservationsRequest) Reset() {
	*x = GetConnectionObservationsRequest{}
	mi := &file_operations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionObservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionObservationsRequest) ProtoMessage() {}

func (x *GetConnectionObservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionObservationsRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionObservationsRequest) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{6}
}

func (x *GetConnectionObservationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetConnectionObservationsRequest) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *GetConnectionObservationsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetConnectionObservationsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetConnectionObservationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetConnectionObservationsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetConnectionObservationsRequest) GetIncludeCurrent() bool {
	if x != nil {
		return x.IncludeCurrent
	}
	return false
}

type ConnectionObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`            // online | offline
	ObservedAt    int64                  `protobuf:"varint,4,opt,name=observedAt,proto3" json:"observedAt,omitempty"` // UnixNano
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionObservation) Reset() {
	*x = ConnectionObservation{}
	mi := &file_operations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionObservation) ProtoMessage() {}

func (x *ConnectionObservation) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionObservation.ProtoReflect.Descriptor instead.
func (*ConnectionObservation) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectionObservation) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionObservation) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ConnectionObservation) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ConnectionObservation) GetObservedAt() int64 {
	if x != nil {
		return x.ObservedAt
	}
	return 0
}

func (x *ConnectionObservation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CurrentConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	ObservedAt    int64                  `protobuf:"varint,4,opt,name=observedAt,proto3" json:"observedAt,omitempty"` // UnixNano
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`          // ws-conn-table | redis-login | unknown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentConnection) Reset() {
	*x = CurrentConnection{}
	mi := &file_operations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentConnection) ProtoMessage() {}

func (x *CurrentConnection) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentConnection.ProtoReflect.Descriptor instead.
func (*CurrentConnection) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{8}
}

func (x *CurrentConnection) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *CurrentConnection) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *CurrentConnection) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CurrentConnection) GetObservedAt() int64 {
	if x != nil {
		return x.ObservedAt
	}
	return 0
}

func (x *CurrentConnection) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GetConnectionObservationsResponse struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Observations   []*ConnectionObservation `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`
	Current        *CurrentConnection       `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	Complete       bool                     `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	Truncated      bool                     `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"`
	NextCursor     string                   `protobuf:"bytes,5,opt,name=nextCursor,proto3" json:"nextCursor,omitempty"`
	Note           string                   `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	CoverageStatus string                   `protobuf:"bytes,7,opt,name=coverageStatus,proto3" json:"coverageStatus,omitempty"`
	EventsDropped  uint64                   `protobuf:"varint,8,opt,name=eventsDropped,proto3" json:"eventsDropped,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConnectionObservationsResponse) Reset() {
	*x = GetConnectionObservationsResponse{}
	mi := &file_operations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionObservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionObservationsResponse) ProtoMessage() {}

func (x *GetConnectionObservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionObservationsResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionObservationsResponse) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{9}
}

func (x *GetConnectionObservationsResponse) GetObservations() []*ConnectionObservation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *GetConnectionObservationsResponse) GetCurrent() *CurrentConnection {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *GetConnectionObservationsResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *GetConnectionObservationsResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *GetConnectionObservationsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetConnectionObservationsResponse) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *GetConnectionObservationsResponse) GetCoverageStatus() string {
	if x != nil {
		return x.CoverageStatus
	}
	return ""
}

func (x *GetConnectionObservationsResponse) GetEventsDropped() uint64 {
	if x != nil {
		return x.EventsDropped
	}
	return 0
}

type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_operations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{10}
}

type GetCapabilitiesResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MessageSearch        string                 `protobuf:"bytes,11,opt,name=messageSearch,proto3" json:"messageSearch,omitempty"` // 老服务未返回时客户端必须视为不支持
	MessageRecord        string                 `protobuf:"bytes,1,opt,name=messageRecord,proto3" json:"messageRecord,omitempty"`
	MessageTimeline      string                 `protobuf:"bytes,2,opt,name=messageTimeline,proto3" json:"messageTimeline,omitempty"`
	DeliveryEvents       string                 `protobuf:"bytes,3,opt,name=deliveryEvents,proto3" json:"deliveryEvents,omitempty"`
	HistoricalConnection string                 `protobuf:"bytes,4,opt,name=historicalConnection,proto3" json:"historicalConnection,omitempty"`
	AckHistory           string                 `protobuf:"bytes,5,opt,name=ackHistory,proto3" json:"ackHistory,omitempty"`
	WriteFailureEvents   string                 `protobuf:"bytes,6,opt,name=writeFailureEvents,proto3" json:"writeFailureEvents,omitempty"`
	ReadConfirmation     string                 `protobuf:"bytes,7,opt,name=readConfirmation,proto3" json:"readConfirmation,omitempty"`
	ObservedAt           int64                  `protobuf:"varint,8,opt,name=observedAt,proto3" json:"observedAt,omitempty"` // UnixNano
	ObservationEnabled   string                 `protobuf:"bytes,9,opt,name=observationEnabled,proto3" json:"observationEnabled,omitempty"`
	AckMode              string                 `protobuf:"bytes,10,opt,name=ackMode,proto3" json:"ackMode,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_operations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{11}
}

func (x *GetCapabilitiesResponse) GetMessageSearch() string {
	if x != nil {
		return x.MessageSearch
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetMessageRecord() string {
	if x != nil {
		return x.MessageRecord
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetMessageTimeline() string {
	if x != nil {
		return x.MessageTimeline
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetDeliveryEvents() string {
	if x != nil {
		return x.DeliveryEvents
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetHistoricalConnection() string {
	if x != nil {
		return x.HistoricalConnection
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetAckHistory() string {
	if x != nil {
		return x.AckHistory
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetWriteFailureEvents() string {
	if x != nil {
		return x.WriteFailureEvents
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetReadConfirmation() string {
	if x != nil {
		return x.ReadConfirmation
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetObservedAt() int64 {
	if x != nil {
		return x.ObservedAt
	}
	return 0
}

func (x *GetCapabilitiesResponse) GetObservationEnabled() string {
	if x != nil {
		return x.ObservationEnabled
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetAckMode() string {
	if x != nil {
		return x.AckMode
	}
	return ""
}

var File_operations_proto protoreflect.FileDescriptor

const file_operations_proto_rawDesc = "" +
	"\n" +
	"\x10operations.proto\x12\n" +
	"operations\"\xcd\x04\n" +
	"\fMessageEvent\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\"\n" +
	"\feventVersion\x18\x02 \x01(\x05R\feventVersion\x12\x1c\n" +
	"\teventType\x18\x03 \x01(\tR\teventType\x12\x1c\n" +
	"\tmessageId\x18\x04 \x01(\tR\tmessageId\x12(\n" +
	"\x0fclientMessageId\x18\x05 \x01(\tR\x0fclientMessageId\x12$\n" +
	"\rcorrelationId\x18\x06 \x01(\tR\rcorrelationId\x12&\n" +
	"\x0econversationId\x18\a \x01(\tR\x0econversationId\x12\x1a\n" +
	"\bsenderId\x18\b \x01(\tR\bsenderId\x12\x1e\n" +
	"\n" +
	"receiverId\x18\t \x01(\tR\n" +
	"receiverId\x12\x1c\n" +
	"\tattemptId\x18\n" +
	" \x01(\tR\tattemptId\x12\x1e\n" +
	"\n" +
	"occurredAt\x18\v \x01(\x03R\n" +
	"occurredAt\x12\x16\n" +
	"\x06source\x18\f \x01(\tR\x06source\x12\x1c\n" +
	"\terrorCode\x18\r \x01(\tR\terrorCode\x12\x1a\n" +
	"\bsequence\x18\x0e \x01(\x03R\bsequence\x12B\n" +
	"\bmetadata\x18\x0f \x03(\v2&.operations.MessageEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x19GetMessageTimelineRequest\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\tR\tmessageId\x12\x1c\n" +
	"\tstartTime\x18\x02 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x03 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"\x94\x02\n" +
	"\x1aGetMessageTimelineResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.operations.MessageEventR\x06events\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\x12\x1e\n" +
	"\n" +
	"nextCursor\x18\x04 \x01(\tR\n" +
	"nextCursor\x12\x1c\n" +
	"\tmessageId\x18\x05 \x01(\tR\tmessageId\x12&\n" +
	"\x0ecoverageStatus\x18\x06 \x01(\tR\x0ecoverageStatus\x12$\n" +
	"\reventsDropped\x18\a \x01(\x04R\reventsDropped\"\x88\x01\n" +
	"\x1aGetDeliveryTimelineRequest\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\tR\tmessageId\x12\x1e\n" +
	"\n" +
	"receiverId\x18\x02 \x01(\tR\n" +
	"receiverId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"\x97\x03\n" +
	"\rDeliveryEvent\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\x1c\n" +
	"\teventType\x18\x02 \x01(\tR\teventType\x12\x1c\n" +
	"\tmessageId\x18\x03 \x01(\tR\tmessageId\x12\x1e\n" +
	"\n" +
	"receiverId\x18\x04 \x01(\tR\n" +
	"receiverId\x12\x1c\n" +
	"\tattemptId\x18\x05 \x01(\tR\tattemptId\x12\x1e\n" +
	"\n" +
	"occurredAt\x18\x06 \x01(\x03R\n" +
	"occurredAt\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x1c\n" +
	"\terrorCode\x18\b \x01(\tR\terrorCode\x12C\n" +
	"\bmetadata\x18\t \x03(\v2'.operations.DeliveryEvent.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\bevidence\x18\n" +
	" \x01(\tR\bevidence\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x02\n" +
	"\x1bGetDeliveryTimelineResponse\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.operations.DeliveryEventR\x06events\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\x12\x1e\n" +
	"\n" +
	"nextCursor\x18\x04 \x01(\tR\n" +
	"nextCursor\x12\x1c\n" +
	"\tmessageId\x18\x05 \x01(\tR\tmessageId\x12&\n" +
	"\x0ecoverageStatus\x18\x06 \x01(\tR\x0ecoverageStatus\x12$\n" +
	"\reventsDropped\x18\a \x01(\x04R\reventsDropped\"\xd8\x01\n" +
	" GetConnectionObservationsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02at\x18\x02 \x01(\x03R\x02at\x12\x1c\n" +
	"\tstartTime\x18\x03 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x04 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x06 \x01(\tR\x06cursor\x12&\n" +
	"\x0eincludeCurrent\x18\a \x01(\bR\x0eincludeCurrent\"\xa9\x01\n" +
	"\x15ConnectionObservation\x12\"\n" +
	"\fconnectionId\x18\x01 \x01(\tR\fconnectionId\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1e\n" +
	"\n" +
	"observedAt\x18\x04 \x01(\x03R\n" +
	"observedAt\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xa7\x01\n" +
	"\x11CurrentConnection\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\x12\"\n" +
	"\fconnectionId\x18\x02 \x01(\tR\fconnectionId\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x1e\n" +
	"\n" +
	"observedAt\x18\x04 \x01(\x03R\n" +
	"observedAt\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\xdf\x02\n" +
	"!GetConnectionObservationsResponse\x12E\n" +
	"\fobservations\x18\x01 \x03(\v2!.operations.ConnectionObservationR\fobservations\x127\n" +
	"\acurrent\x18\x02 \x01(\v2\x1d.operations.CurrentConnectionR\acurrent\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete\x12\x1c\n" +
	"\ttruncated\x18\x04 \x01(\bR\ttruncated\x12\x1e\n" +
	"\n" +
	"nextCursor\x18\x05 \x01(\tR\n" +
	"nextCursor\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12&\n" +
	"\x0ecoverageStatus\x18\a \x01(\tR\x0ecoverageStatus\x12$\n" +
	"\reventsDropped\x18\b \x01(\x04R\reventsDropped\"\x18\n" +
	"\x16GetCapabilitiesRequest\"\xd1\x03\n" +
	"\x17GetCapabilitiesResponse\x12$\n" +
	"\rmessageSearch\x18\v \x01(\tR\rmessageSearch\x12$\n" +
	"\rmessageRecord\x18\x01 \x01(\tR\rmessageRecord\x12(\n" +
	"\x0fmessageTimeline\x18\x02 \x01(\tR\x0fmessageTimeline\x12&\n" +
	"\x0edeliveryEvents\x18\x03 \x01(\tR\x0edeliveryEvents\x122\n" +
	"\x14historicalConnection\x18\x04 \x01(\tR\x14historicalConnection\x12\x1e\n" +
	"\n" +
	"ackHistory\x18\x05 \x01(\tR\n" +
	"ackHistory\x12.\n" +
	"\x12writeFailureEvents\x18\x06 \x01(\tR\x12writeFailureEvents\x12*\n" +
	"\x10readConfirmation\x18\a \x01(\tR\x10readConfirmation\x12\x1e\n" +
	"\n" +
	"observedAt\x18\b \x01(\x03R\n" +
	"observedAt\x12.\n" +
	"\x12observationEnabled\x18\t \x01(\tR\x12observationEnabled\x12\x18\n" +
	"\aackMode\x18\n" +
	" \x01(\tR\aackMode2\xb5\x03\n" +
	"\x10ObservationQuery\x12c\n" +
	"\x12GetMessageTimeline\x12%.operations.GetMessageTimelineRequest\x1a&.operations.GetMessageTimelineResponse\x12f\n" +
	"\x13GetDeliveryTimeline\x12&.operations.GetDeliveryTimelineRequest\x1a'.operations.GetDeliveryTimelineResponse\x12x\n" +
	"\x19GetConnectionObservations\x12,.operations.GetConnectionObservationsRequest\x1a-.operations.GetConnectionObservationsResponse\x12Z\n" +
	"\x0fGetCapabilities\x12\".operations.GetCapabilitiesRequest\x1a#.operations.GetCapabilitiesResponseB\x0eZ\f./operationsb\x06proto3"

var (
	file_operations_proto_rawDescOnce sync.Once
	file_operations_proto_rawDescData []byte
)

func file_operations_proto_rawDescGZIP() []byte {
	file_operations_proto_rawDescOnce.Do(func() {
		file_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operations_proto_rawDesc), len(file_operations_proto_rawDesc)))
	})
	return file_operations_proto_rawDescData
}

var file_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_operations_proto_goTypes = []any{
	(*MessageEvent)(nil),                      // 0: operations.MessageEvent
	(*GetMessageTimelineRequest)(nil),         // 1: operations.GetMessageTimelineRequest
	(*GetMessageTimelineResponse)(nil),        // 2: operations.GetMessageTimelineResponse
	(*GetDeliveryTimelineRequest)(nil),        // 3: operations.GetDeliveryTimelineRequest
	(*DeliveryEvent)(nil),                     // 4: operations.DeliveryEvent
	(*GetDeliveryTimelineResponse)(nil),       // 5: operations.GetDeliveryTimelineResponse
	(*GetConnectionObservationsRequest)(nil),  // 6: operations.GetConnectionObservationsRequest
	(*ConnectionObservation)(nil),             // 7: operations.ConnectionObservation
	(*CurrentConnection)(nil),                 // 8: operations.CurrentConnection
	(*GetConnectionObservationsResponse)(nil), // 9: operations.GetConnectionObservationsResponse
	(*GetCapabilitiesRequest)(nil),            // 10: operations.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil),           // 11: operations.GetCapabilitiesResponse
	nil,                                       // 12: operations.MessageEvent.MetadataEntry
	nil,                                       // 13: operations.DeliveryEvent.MetadataEntry
}
var file_operations_proto_depIdxs = []int32{
	12, // 0: operations.MessageEvent.metadata:type_name -> operations.MessageEvent.MetadataEntry
	0,  // 1: operations.GetMessageTimelineResponse.events:type_name -> operations.MessageEvent
	13, // 2: operations.DeliveryEvent.metadata:type_name -> operations.DeliveryEvent.MetadataEntry
	4,  // 3: operations.GetDeliveryTimelineResponse.events:type_name -> operations.DeliveryEvent
	7,  // 4: operations.GetConnectionObservationsResponse.observations:type_name -> operations.ConnectionObservation
	8,  // 5: operations.GetConnectionObservationsResponse.current:type_name -> operations.CurrentConnection
	1,  // 6: operations.ObservationQuery.GetMessageTimeline:input_type -> operations.GetMessageTimelineRequest
	3,  // 7: operations.ObservationQuery.GetDeliveryTimeline:input_type -> operations.GetDeliveryTimelineRequest
	6,  // 8: operations.ObservationQuery.GetConnectionObservations:input_type -> operations.GetConnectionObservationsRequest
	10, // 9: operations.ObservationQuery.GetCapabilities:input_type -> operations.GetCapabilitiesRequest
	2,  // 10: operations.ObservationQuery.GetMessageTimeline:output_type -> operations.GetMessageTimelineResponse
	5,  // 11: operations.ObservationQuery.GetDeliveryTimeline:output_type -> operations.GetDeliveryTimelineResponse
	9,  // 12: operations.ObservationQuery.GetConnectionObservations:output_type -> operations.GetConnectionObservationsResponse
	11, // 13: operations.ObservationQuery.GetCapabilities:output_type -> operations.GetCapabilitiesResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_operations_proto_init() }
func file_operations_proto_init() {
	if File_operations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operations_proto_rawDesc), len(file_operations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operations_proto_goTypes,
		DependencyIndexes: file_operations_proto_depIdxs,
		MessageInfos:      file_operations_proto_msgTypes,
	}.Build()
	File_operations_proto = out.File
	file_operations_proto_goTypes = nil
	file_operations_proto_depIdxs = nil
}
