FROM alpine:3.18

# 添加时区处理
# 修正后的时区配置段落
RUN echo -e "https://mirrors.aliyun.com/alpine/v3.15/main\nhttps://mirrors.aliyun.com/alpine/v3.15/community" > /etc/apk/repositories && \
    apk update && \
    apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone
ENV TZ=Asia/Shanghai

# 声明属性变量（只在dockerfile中生效）
ARG SERVER_NAME=social
ARG SERVER_TYPE=rpc

# 声明环境变量（在dockerfile和容器中都生效）
ENV RUN_BIN bin/${SERVER_NAME}-${SERVER_TYPE}
ENV RUN_CONF /${SERVER_NAME}/conf/${SERVER_NAME}.yaml

# 将宿主机内容复制到容器中 左边是宿主机路径 右边是容器路径
RUN mkdir /$SERVER_NAME && mkdir /$SERVER_NAME/bin && mkdir /$SERVER_NAME/conf

#复制编译后的二进制文件
COPY ./bin/$SERVER_NAME-$SERVER_TYPE /$SERVER_NAME/bin/
#复制配置文件
COPY ./apps/$SERVER_NAME/$SERVER_TYPE/etc/dev/$SERVER_NAME.yaml /$SERVER_NAME/conf/


RUN chmod +x /$SERVER_NAME/bin/$SERVER_NAME-$SERVER_TYPE

WORKDIR /$SERVER_NAME

#这个命令可以让我们的docker容器在启动的时候就执行下面的命令
#与CMD不同之处是，在docker run 后跟的命令不能替换它，它仍然会启动的时候执行
#ENTRYPOINT[“SRUN_BIN”，"-f”，“$RUN_CONF"] I/ 这种写法不支持对环境变量的解析。
#您正在使用ENTRYPOINT 的exec形式。与sheLL表单不同，eXec表单不会调用命令sheLL。这意味着正常的外壳处理不会发生。例如，ENTRYPOINT ["eChO","$HOME"]
#将不会在S HOME上进行变量替换。如果要进行sheLL处理，则可以使用sheLL形式或直接执行sheLL，例如：ENTRYPOINT 【“sh"，"-C"，“echo SHOME"]。
ENTRYPOINT ["sh", "-c", "$RUN_BIN -f $RUN_CONF"]
