// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: user_query.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserQuery_FindUserReference_FullMethodName = "/user.UserQuery/FindUserReference"
)

// UserQueryClient is the client API for UserQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 用户领域最小只读投影。仅授权内部服务，不暴露手机号等敏感字段。
type UserQueryClient interface {
	FindUserReference(ctx context.Context, in *UserReferenceRequest, opts ...grpc.CallOption) (*UserReferenceResponse, error)
}

type userQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewUserQueryClient(cc grpc.ClientConnInterface) UserQueryClient {
	return &userQueryClient{cc}
}

func (c *userQueryClient) FindUserReference(ctx context.Context, in *UserReferenceRequest, opts ...grpc.CallOption) (*UserReferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserReferenceResponse)
	err := c.cc.Invoke(ctx, UserQuery_FindUserReference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserQueryServer is the server API for UserQuery service.
// All implementations must embed UnimplementedUserQueryServer
// for forward compatibility.
//
// 用户领域最小只读投影。仅授权内部服务，不暴露手机号等敏感字段。
type UserQueryServer interface {
	FindUserReference(context.Context, *UserReferenceRequest) (*UserReferenceResponse, error)
	mustEmbedUnimplementedUserQueryServer()
}

// UnimplementedUserQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserQueryServer struct{}

func (UnimplementedUserQueryServer) FindUserReference(context.Context, *UserReferenceRequest) (*UserReferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindUserReference not implemented")
}
func (UnimplementedUserQueryServer) mustEmbedUnimplementedUserQueryServer() {}
func (UnimplementedUserQueryServer) testEmbeddedByValue()                   {}

// UnsafeUserQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserQueryServer will
// result in compilation errors.
type UnsafeUserQueryServer interface {
	mustEmbedUnimplementedUserQueryServer()
}

func RegisterUserQueryServer(s grpc.ServiceRegistrar, srv UserQueryServer) {
	// If the following call panics, it indicates UnimplementedUserQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserQuery_ServiceDesc, srv)
}

func _UserQuery_FindUserReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServer).FindUserReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserQuery_FindUserReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServer).FindUserReference(ctx, req.(*UserReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserQuery_ServiceDesc is the grpc.ServiceDesc for UserQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserQuery",
	HandlerType: (*UserQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindUserReference",
			Handler:    _UserQuery_FindUserReference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_query.proto",
}
