// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: user_query.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserReferenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 三种条件必须且只能选一种，避免隐式优先级。
	UserId        string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname      string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Phone         string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Limit         int32  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // 默认 50，最多 200
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReferenceRequest) Reset() {
	*x = UserReferenceRequest{}
	mi := &file_user_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReferenceRequest) ProtoMessage() {}

func (x *UserReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReferenceRequest.ProtoReflect.Descriptor instead.
func (*UserReferenceRequest) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{0}
}

func (x *UserReferenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserReferenceRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserReferenceRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserReferenceRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UserQueryReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	ObservedAt    int64                  `protobuf:"varint,4,opt,name=observedAt,proto3" json:"observedAt,omitempty"` // UnixNano
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserQueryReference) Reset() {
	*x = UserQueryReference{}
	mi := &file_user_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserQueryReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryReference) ProtoMessage() {}

func (x *UserQueryReference) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryReference.ProtoReflect.Descriptor instead.
func (*UserQueryReference) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{1}
}

func (x *UserQueryReference) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserQueryReference) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserQueryReference) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserQueryReference) GetObservedAt() int64 {
	if x != nil {
		return x.ObservedAt
	}
	return 0
}

type UserReferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserQueryReference  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Truncated     bool                   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReferenceResponse) Reset() {
	*x = UserReferenceResponse{}
	mi := &file_user_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReferenceResponse) ProtoMessage() {}

func (x *UserReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReferenceResponse.ProtoReflect.Descriptor instead.
func (*UserReferenceResponse) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{2}
}

func (x *UserReferenceResponse) GetUsers() []*UserQueryReference {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserReferenceResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

var File_user_query_proto protoreflect.FileDescriptor

const file_user_query_proto_rawDesc = "" +
	"\n" +
	"\x10user_query.proto\x12\x04user\"v\n" +
	"\x14UserReferenceRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x86\x01\n" +
	"\x12UserQueryReference\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\vdisplayName\x18\x02 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"observedAt\x18\x04 \x01(\x03R\n" +
	"observedAt\"e\n" +
	"\x15UserReferenceResponse\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.user.UserQueryReferenceR\x05users\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated2Y\n" +
	"\tUserQuery\x12L\n" +
	"\x11FindUserReference\x12\x1a.user.UserReferenceRequest\x1a\x1b.user.UserReferenceResponseB)Z'github.com/IM_System/apps/user/rpc/userb\x06proto3"

var (
	file_user_query_proto_rawDescOnce sync.Once
	file_user_query_proto_rawDescData []byte
)

func file_user_query_proto_rawDescGZIP() []byte {
	file_user_query_proto_rawDescOnce.Do(func() {
		file_user_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_query_proto_rawDesc), len(file_user_query_proto_rawDesc)))
	})
	return file_user_query_proto_rawDescData
}

var file_user_query_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_query_proto_goTypes = []any{
	(*UserReferenceRequest)(nil),  // 0: user.UserReferenceRequest
	(*UserQueryReference)(nil),    // 1: user.UserQueryReference
	(*UserReferenceResponse)(nil), // 2: user.UserReferenceResponse
}
var file_user_query_proto_depIdxs = []int32{
	1, // 0: user.UserReferenceResponse.users:type_name -> user.UserQueryReference
	0, // 1: user.UserQuery.FindUserReference:input_type -> user.UserReferenceRequest
	2, // 2: user.UserQuery.FindUserReference:output_type -> user.UserReferenceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_query_proto_init() }
func file_user_query_proto_init() {
	if File_user_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_query_proto_rawDesc), len(file_user_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_query_proto_goTypes,
		DependencyIndexes: file_user_query_proto_depIdxs,
		MessageInfos:      file_user_query_proto_msgTypes,
	}.Build()
	File_user_query_proto = out.File
	file_user_query_proto_goTypes = nil
	file_user_query_proto_depIdxs = nil
}
